Repository FaceTheFacts/backend, pull requests merged in 2021-12, with the labels that each got.

#109 Feature/107/api/versioning
  src/api/main.py
  src/api/versions/v1.py
  tests/api/test_crud.py
  tests/api/versions/__init__.py
  tests/api/versions/test_v1.py
Labels: enhancement

#112 Feature/110/route/politician media
  src/api/crud.py
  src/api/schemas.py
  src/api/utils/read_url.py
  src/api/versions/v1.py
  tests/api/versions/test_v1.py
Labels: enhancement

#116 Feature/115/update route/search and image scanner
  src/api/crud.py
  src/api/versions/v1.py
  tests/api/versions/test_v1.py
Labels: bug, enhancement

#129 Hotfix/120/addLicense
  LICENSE
Labels: documentation

#127 Feature/117/politician id route/changing return data
  src/api/crud.py
  src/api/schemas.py
  src/api/utils/politician.py
  src/api/versions/v1.py
  tests/api/versions/test_mockup_v1.py
  tests/api/versions/test_v1.py
  tests/db/mock_up_database.py
Labels: enhancement
